version: "3"

services:
  db:
   image: mysql:5.7
   container_name: sudheer_demo
   environment:
    MYSQL_ROOT_PASSWORD: 1234
    MYSQL_DATABASE: test_db
    MYSQL_USER: demo
    MYSQL_PASSWORD: demo
   ports:
     - "9906:3306"
   networks:
    - frontend
  web:
    image: php:7.2.2-apache
    container_name: php_web
    depends_on:
      - db
    volumes:
      - ./php/:/var/www/html/
    ports:
      - "8100:80"
    networks:
     - frontend
networks:
 frontend: 
    
